// src/components/Counter.tsx
import React, { useState } from 'react';
import { useStore } from '@nanostores/react';
import { count } from '../stores/count';

export default function Example() {
  // Declare a new state variable, which we'll call "count"
  const $count = useStore(count);

  return (
    <div className='react-component'>
      <p>You clicked {$count} times</p>
      <button onClick={() => count.set($count + 1)}>
        Click me
      </button>
    </div>
  );
}

// src/components/Counter.vue
<template>
  <div className="vue-component">
    <Hello />
    <div>
      {{$count}}
    </div>
    <button @click="() => count.set($count + 1)">
      + 1
    </button>
    <div style="border:1px solid black; padding: 4px;">
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import Hello from './AnotherComponent.vue'

import { count } from '../stores/count'
import { useStore } from '@nanostores/vue'

const $count = useStore(count)
</script>

<style scoped>
.slot {
  border: 1px solid black;
  padding: 4px;
}
</style>
